<?php

namespace Database\Seeders;

use App\Models\ReservaOtorgacion;
use Illuminate\Database\Seeder;

class HomonimiaReservaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ReservaOtorgacion::create(['fecha_reg' => '2022-02-21', 'hr' => 9052, 'entidad' => 'CONSEJO MINERO DE GOBERNACIONES', 'sigla' => 'COMINGOB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-52', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-03', 'representante' => 'ESTEBAN ALFREDO PATI PARI', 'telefono' => '74029917', 'correo' => 'hmenchaca@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-02-22', 'hr' => 9053, 'entidad' => 'ASOCIACION INTERNACIONAL DE AGENTES PROFESIONALES DE ADUANA', 'sigla' => 'ASAPRA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-53', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-04', 'representante' => 'ALEXINA FLORES GALLEGOS', 'telefono' => '69830436', 'correo' => 'aflores@cnda.org.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-02-23', 'hr' => 9054, 'entidad' => 'ASOCIACION DE FUNDADORES Y AUTONOMISTAS DE LA UNIVERSIDAD PUBLICA DE EL ALTO', 'sigla' => 'AFA-UPEA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-54', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-05', 'representante' => 'JOSE LUIS QUENALLATA QUENALLATA', 'telefono' => '71577245', 'correo' => '2000afaupea2003@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-02-24', 'hr' => 9055, 'entidad' => 'FUNDACION EDUCATIVA UNIVERSIDAD CIENTIFICA DE LA PAZ', 'sigla' => 'U.C.L.A.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-55', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-06', 'representante' => 'FOSTER MARAÑON SALINAS ', 'telefono' => '68049394', 'correo' => 'drfostermaranon@gmail.com ', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-02-25', 'hr' => 9056, 'entidad' => 'CAMARA BOLIVIANA DE OPERADORES LOGISTICOS Y OTM', 'sigla' => 'CABOL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-56', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-07', 'representante' => 'MARIA DE LA ESPERANZA LANDIVAR POLO', 'telefono' => '77718206', 'correo' => 'cabolotm@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-02-26', 'hr' => 9057, 'entidad' => 'FUNDACION JOSE KENTENICH', 'sigla' => 'FJK', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-57', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-08', 'representante' => 'LUZ MARINA GUTIERREZ REGUERIN', 'telefono' => '78112784', 'correo' => 'nicolasvalverde@wayarabogados.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-02-27', 'hr' => 9058, 'entidad' => 'ONG COMUNIDADES SOSTENIBLES', 'sigla' => 'OCS', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-58', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-09', 'representante' => 'LUZ MARINA GUTIERREZ REGUERIN', 'telefono' => '78112784', 'correo' => 'luzgutierrez@wayarabogados.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-02-28', 'hr' => 9059, 'entidad' => 'CAMARA DE EMPRESAS DE LA INDUSTRIA DE EVENTOS DE BOLIVIA', 'sigla' => 'CABIE ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-59', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-10', 'representante' => 'KATHERINE ROSARIO DEL RIO BRAVO', 'telefono' => '70514101', 'correo' => 'cabiebolivia1@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-01', 'hr' => 9060, 'entidad' => 'FEDERACION BOLIVIANA DE KUNG FU-WUSHU', 'sigla' => 'FBKFW', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-60', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-11', 'representante' => 'FERNANDO ZEBALLOS GUTIERREZ', 'telefono' => '72511636', 'correo' => 'f.zeballos.gutierrez@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-02', 'hr' => 9061, 'entidad' => 'FUNDACION MUNASIM KULLAKITA ', 'sigla' => 'FMK', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-61', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-12', 'representante' => 'RICCARDO GIAVARINI', 'telefono' => '71933142', 'correo' => 'ciledezma@hotmail.com ', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-03', 'hr' => 9062, 'entidad' => 'FUNDACION JERUSALEN', 'sigla' => 'FUNDALEN', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-62', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-13', 'representante' => 'ERICK HUMBERTO PEINADO MENDEZ', 'telefono' => '75008330', 'correo' => 'peinadohumberto@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-04', 'hr' => 9063, 'entidad' => 'CAMARA BOLIVIANA DE MEDIOS DE COMUNICACION ', 'sigla' => 'CABOMEC', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-63', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-14', 'representante' => 'ALFREDO SALAZAR TARQUINO', 'telefono' => '2906913', 'correo' => 'alfredo.elalto@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-05', 'hr' => 9064, 'entidad' => 'ASOCIACION BOLIVIANA DE COACHES ONTOLOGICOS PROFESIONALES', 'sigla' => 'ABCOP', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-64', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-15', 'representante' => 'FERNANDO ZEBALLOS GUTIERREZ', 'telefono' => '72511636', 'correo' => 'f.zeballos.gutierrez@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-06', 'hr' => 9065, 'entidad' => 'CAMARA NACIONAL INMOBILIARIA DE BOLIVIA ', 'sigla' => 'CANIBOL (DE BAJA)', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-65', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-16', 'representante' => 'JARHLIN VARGAS TERRAZAS', 'telefono' => '70009164', 'correo' => 'camaranacionalinmobiliariabolivia@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-07', 'hr' => 9066, 'entidad' => 'FUNDACION FENCOMIN ', 'sigla' => 'FFMCMB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-66', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-17', 'representante' => 'JUAN STANISLAO VILLEGAS', 'telefono' => '67006883', 'correo' => 'camaranacionalinmobiliariabolivia@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-08', 'hr' => 9067, 'entidad' => 'FORTALECIMIENTO ESTRATEGICO PARA EL DESARROLLO SOSTENIBLE ', 'sigla' => 'FEDES BOLIVIA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-67', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-18', 'representante' => 'TEDDY HENRY VILLCA ALVINO ', 'telefono' => '75276377', 'correo' => 'thva_t@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-09', 'hr' => 9068, 'entidad' => 'FUNDACION PARA LA INVESTIGACION Y PREVENCION DEL CANCER Y ENFERMEDADES CRONICAS ', 'sigla' => 'FIPCC', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-68', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-19', 'representante' => 'CARLOS MERINO TROCHE', 'telefono' => '69722905', 'correo' => 'carlosmerino40@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-10', 'hr' => 9069, 'entidad' => 'FUNDACION HABITAT Y DESARROLLO PARA EL FOMENTO DE LA AGRICULTURA, ECOLOGIA Y TECNOLOGIA', 'sigla' => 'FUNDAHABITAT', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-69', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-20', 'representante' => 'OMAR BLACUTT VIVIAN ', 'telefono' => '78004138', 'correo' => 'omarblacutt@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-11', 'hr' => 9070, 'entidad' => 'FUNDACION UNIVERSIDAD NUEVA INNOVACION ', 'sigla' => 'UNI ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-70', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-21', 'representante' => 'OMAR BLACUTT VIVIAN ', 'telefono' => '78004138', 'correo' => 'omarblacutt@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-12', 'hr' => 9071, 'entidad' => 'FUNDACION DARTE AMOR', 'sigla' => 'FUNDAMOR', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-71', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-22', 'representante' => 'TITO RONALD ARAMAYO CARBALLO', 'telefono' => '76083782', 'correo' => 'ronald_arac@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-13', 'hr' => 9072, 'entidad' => 'ONG KACHARIY', 'sigla' => 'KACHARIY ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-72', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-23', 'representante' => 'ANGELICA BLANCA ECHALAR ', 'telefono' => '70781116', 'correo' => 'angelica_echalar@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-14', 'hr' => 9073, 'entidad' => 'CONFEDERACION DE LOS PUEBLOS ORIGINARIOS DE LA NACION QUECHUA DE BOLIVIA ', 'sigla' => 'C.P.O.N.Q.B.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-73', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-24', 'representante' => 'CHRISTIAN MOISES CORTES PEREZ', 'telefono' => '78933653', 'correo' => 'christian_moises1@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-15', 'hr' => 9074, 'entidad' => 'ASOCIACION BOLIVIANA DE ORNITOLOGIA ', 'sigla' => 'ASBOR ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-74', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-25', 'representante' => 'DANIELA ARLETTE MORALES MORENO ', 'telefono' => '70679125', 'correo' => 'angelica_echalar@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-16', 'hr' => 9075, 'entidad' => 'VENMUNDO VENEZOLANOS RESIDENTES EN BOLIVIA', 'sigla' => 'VRB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-75', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-26', 'representante' => 'CINTIA MONICA PEÑALOZA SUAREZ', 'telefono' => '730045554', 'correo' => 'venmundo.bolivia@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-17', 'hr' => 9076, 'entidad' => 'COMISION NACIONAL DE DEPORTISTAS, ENTRENADORES Y PROFESIONALES DEL DEPORTE BOLIVIANO', 'sigla' => 'CONDEBO', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-76', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-27', 'representante' => 'DUBERTY FLORES MAMANI ', 'telefono' => '73009870', 'correo' => 'deportistas.asociacion@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-18', 'hr' => 9077, 'entidad' => 'CAMARA BINACIONAL DE COMERCIO E INDUSTRIA BOLIVIANO-PARAGUAYA', 'sigla' => 'CCIBOLPAR ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-77', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-28', 'representante' => 'SUSANA MOREIRA ', 'telefono' => '69962368', 'correo' => 'deportistas.asociacion@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-19', 'hr' => 9078, 'entidad' => 'CAMARA DE EMPRESAS Y SERVICIOS PARA EVENTOS BOLIVIA ', 'sigla' => 'CAESEBOL ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-78', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-29', 'representante' => 'JUAN JOSE YAÑEZ TORREZ', 'telefono' => '69962368', 'correo' => 'liturralde@kantutani.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-20', 'hr' => 9079, 'entidad' => 'FUNDACION INVERIT', 'sigla' => 'FUNIT', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-79', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-30', 'representante' => 'LUIS ENRIQUE GONZALO ITURRALDE MORENO', 'telefono' => '69720300', 'correo' => 'liturralde@kantutani.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-21', 'hr' => 9080, 'entidad' => 'FUNDACION FIRMEZA ', 'sigla' => 'FUF', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-80', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-03-31', 'representante' => 'JUAN CARLOS MEDRANO GONZALES ', 'telefono' => '69213344', 'correo' => 'liturralde@kantutani.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-22', 'hr' => 9081, 'entidad' => 'FUNDACION SEMILLAS DE BENDICION ', 'sigla' => 'FSB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-81', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-01', 'representante' => 'FRANKLIN REYNALDO RODRIGUEZ COARITE', 'telefono' => '77284724', 'correo' => 'info@vivaboliviaps.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-23', 'hr' => 9082, 'entidad' => 'ASOCIACION NACIONAL DE EMPRENDEDORES BOLIVIA PROGRESA', 'sigla' => 'ANEBOP ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-82', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-02', 'representante' => 'GRISEL VICTORIA CARVAJAL ROJAS', 'telefono' => '76003577', 'correo' => 'wjmendez@emprendedores.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-24', 'hr' => 9083, 'entidad' => 'CAMARA NACIONAL INMOBILIARIA DE BOLIVIA ', 'sigla' => 'CNIB ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-83', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-03', 'representante' => 'JAMIL MIRKO PARDO CHAVEZ', 'telefono' => '70009164', 'correo' => 'camaranacionalinmobiliariabolivia@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-25', 'hr' => 9084, 'entidad' => 'ASOCIACION BOLIVIANA DE ETICA Y COMPLIANCE', 'sigla' => 'ASBEC', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-84', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-04', 'representante' => 'CLAUDIA ANDREA GARCIA GARCIA PAZ ', 'telefono' => '70721897', 'correo' => 'claudiagarciapaz@gmail.com ', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-26', 'hr' => 9085, 'entidad' => 'ASOCIACION NACIONAL DE PADRES DE FAMILIA DE COLEGIOS PRIVADOS DE BOLIVIA ', 'sigla' => 'ASOPPFF', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-85', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-05', 'representante' => 'HELEN AMGELICA RODRIGUEZ CORNEJO ', 'telefono' => '65429766', 'correo' => 'jannethdylan@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-27', 'hr' => 9086, 'entidad' => 'FUNDACION UNIDOS PARA EL DESARROLLO DE BOLIVIA', 'sigla' => 'FUDEB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-86', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-06', 'representante' => 'JAVIER CARLOS DURAN PEREZ', 'telefono' => '72534342', 'correo' => 'jdrecursoshumanos@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-28', 'hr' => 9087, 'entidad' => 'ACADEMIA BOLIVIANA DE ESTUDIOS CONSTITUCIONALES', 'sigla' => 'ABEC', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-87', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-07', 'representante' => 'INGRID ALEJANDRA SANCHEZ CARDOZO', 'telefono' => '79821225', 'correo' => 'ingrid@herrerabogados.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-29', 'hr' => 9088, 'entidad' => 'ASOCIACION BOLIVIANA DE COMERCIO ELECTRONICO', 'sigla' => 'ABCE', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-88', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-08', 'representante' => 'RICARDO DENIS VELASCO PAREJAS', 'telefono' => '77311722', 'correo' => 'presidencia@abce.org.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-30', 'hr' => 9089, 'entidad' => 'FUNDACION ESPACIO GENERACIONAL EDUCATIVO SOCIOCULTURAL - BOLIVIA', 'sigla' => 'EGES BOLIVIA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-89', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-09', 'representante' => 'LASTENIA ELIS AYAVIRI ALVAREZ', 'telefono' => '69911995', 'correo' => 'espacioeges@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-03-31', 'hr' => 9090, 'entidad' => 'EDUCA BOLIVIA', 'sigla' => 'E.B.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-90', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-10', 'representante' => 'ANA MARIA SANCHEZ MOLINA', 'telefono' => '73646561', 'correo' => 'ana_msm@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-01', 'hr' => 9091, 'entidad' => 'FUNDACION CARLA LUCIA', 'sigla' => 'FCL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-91', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-11', 'representante' => 'ANTONIO ALBERTO CASSAP URZAGASTE', 'telefono' => '76181811', 'correo' => 'beto_cassap@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-02', 'hr' => 9092, 'entidad' => 'FUNDACION MUJERES', 'sigla' => 'FUM', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-92', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-12', 'representante' => 'LOURDES ANDREA FERNANDEZ BLACUTT', 'telefono' => '74729959', 'correo' => 'andreafernandezblacutt@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-03', 'hr' => 9093, 'entidad' => 'ONG REVERDESER', 'sigla' => 'IONGFE', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-93', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-13', 'representante' => 'EDWIN POOL MARQUEZ PINTO', 'telefono' => '69962368', 'correo' => 'decosbolivia@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-04', 'hr' => 9094, 'entidad' => 'FUNDACION TREBOL ', 'sigla' => 'FUNTREBOL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-94', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-14', 'representante' => 'CARMEN ISABEL HURTADO AZURDUY', 'telefono' => '8001007707', 'correo' => 'ihurtado@trebol.com.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-05', 'hr' => 9095, 'entidad' => 'CAMARA BOLIVIANA DE COMERCIALIZADORES DE HIDROCARBUROS', 'sigla' => 'CBCH', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-95', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-15', 'representante' => 'JIMMY R. HILARI MAMANI', 'telefono' => '72985108', 'correo' => 'camaracbch@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-06', 'hr' => 9096, 'entidad' => 'ONG ÑANDE BOLIVIA', 'sigla' => 'ÑB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-96', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-16', 'representante' => 'CHRISTIAN EDUARDO MONJE', 'telefono' => '74057667', 'correo' => 'nandeboliviaddhh@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-07', 'hr' => 9097, 'entidad' => 'ONG CENTRO FAMILIAR CRISTIANO "MI CASA"', 'sigla' => 'ONFA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-97', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-17', 'representante' => 'JAVIER SOCRATES VALDA MIRANDA', 'telefono' => '79551847', 'correo' => 'alinepat@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-08', 'hr' => 9098, 'entidad' => 'CAMARA NACIONAL DE EMPRESAS DE SEGURIDAD PRIVADA', 'sigla' => 'CANASEP', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-98', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-18', 'representante' => 'JOSE RUDY GALIER MACHACA', 'telefono' => '76203794', 'correo' => 'jose_rgalier@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-09', 'hr' => 9099, 'entidad' => 'WOMEN IN MINING BOLIVIA', 'sigla' => 'WIM', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-99', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-19', 'representante' => 'ANA MARIA ARANIBAR', 'telefono' => '70684024', 'correo' => 'winbolivia2019@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-10', 'hr' => 9100, 'entidad' => 'ONG "JCI BOLIVIA"', 'sigla' => 'JCI ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-100', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-20', 'representante' => 'SEBASTIAN ANDRES ARZE PANDO', 'telefono' => '76400789', 'correo' => 'mariabelenguerraflores@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-11', 'hr' => 9101, 'entidad' => 'ASOCIACION TURISTICA COMUNITARIA SADIRI LODGE', 'sigla' => 'SADIRI LODGE', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-101', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-21', 'representante' => 'RUBEN FELIPE PINTO VARGAS', 'telefono' => '79153605', 'correo' => 'rubenpintovargas@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-12', 'hr' => 9102, 'entidad' => 'CENTRO DE DERECHOS DEL CONTRIBUYENTE', 'sigla' => 'CEDC', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-102', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-22', 'representante' => 'MIGUEL ANGEL GUMICIO NOGUEDA', 'telefono' => '69009374', 'correo' => 'mgumucio@ppolegal.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-13', 'hr' => 9103, 'entidad' => 'SOCIEDAD DE INGENIEROS QUIMICOS DE BOLIVIA', 'sigla' => 'SIQB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-103', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-23', 'representante' => 'RONALD CHAVARRIA ZABALA', 'telefono' => '71626966', 'correo' => 'ronaldchavarriazabala@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-14', 'hr' => 9104, 'entidad' => 'FUNDACION "BOLIVIA A PASO FIRME"', 'sigla' => 'FUBAPF', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-104', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-24', 'representante' => 'ANTON NAVA IVANOV', 'telefono' => '76731160', 'correo' => 'navaanton@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-15', 'hr' => 9105, 'entidad' => 'FUNDACION UNIVALLE', 'sigla' => 'UNI ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-105', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-25', 'representante' => 'GONZALO VICENTE RUIZ OSTRIAS', 'telefono' => '4318800', 'correo' => 'exambranag@univalle.edu', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-16', 'hr' => 9106, 'entidad' => 'FUNDACION "YANAPTHASIÑANI JILAPURA"', 'sigla' => 'FYJ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-106', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-26', 'representante' => 'ALEX SIMON ACOCHIRI ESCALANTE', 'telefono' => '77591913', 'correo' => 'a.acochiri@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-17', 'hr' => 9107, 'entidad' => 'ONG VASTOS DESAFIOS', 'sigla' => 'VD', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-107', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-27', 'representante' => 'JAVIER SANDRO ALEGRE PIZARRO', 'telefono' => '68125159', 'correo' => 'js_alpiz@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-18', 'hr' => 9108, 'entidad' => 'ASOCIACION DE MEDICOS GRADUADOS EN EL EXTRANJERO', 'sigla' => 'AMGE', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-108', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-28', 'representante' => 'WILBERTH BARRAL', 'telefono' => '68140068', 'correo' => 'asomedbol@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-19', 'hr' => 9109, 'entidad' => 'ASOCIACIÓN BOLIVIANA DE FUTSAL', 'sigla' => 'ABFS', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-109', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-29', 'representante' => 'ERROL MENDOZA DURAN', 'telefono' => '75241829', 'correo' => 'abfs.presidente@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-20', 'hr' => 9110, 'entidad' => 'CONFEDERACION NACIONAL DE NACIONES INDIGENAS Y ORIGINARIAS DE BOLIVIA', 'sigla' => 'CONNIOB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-110', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-04-30', 'representante' => 'ROBERTO MAMANI PAREDES', 'telefono' => '76760536', 'correo' => 'glendayq@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-21', 'hr' => 9111, 'entidad' => 'FUNDACION MULTIDISCIPLINARIA PRODESARROLLO Y SOCIAL', 'sigla' => 'FUMPROS', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-111', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-01', 'representante' => 'JAVIER CARLOS DURAN PEREZ', 'telefono' => '72534642', 'correo' => 'jdrecursoshumanos@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-22', 'hr' => 9112, 'entidad' => 'FEDERACION BOLIVIANA DE FUTBOL DE SALON A.M.F.', 'sigla' => 'FBFS - AMF', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-112', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-02', 'representante' => 'HORACIO AURELIO ZAMBRANA CARDENAS', 'telefono' => '72181466', 'correo' => 'federacionbolivianafutbolsalon@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-23', 'hr' => 9113, 'entidad' => 'ONG EL PODER DE LAS CULTURAS', 'sigla' => 'ONG', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-113', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-03', 'representante' => 'HORTENCIA GLENDA YAÑEZ QUISBERT', 'telefono' => '76266700', 'correo' => 'glendayq@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-24', 'hr' => 9114, 'entidad' => 'ONG LIDER - LIBERTAD Y DESARROLLO', 'sigla' => 'LIDER', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-114', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-04', 'representante' => 'PAOLA ANDREA OLIVARES CORDERO', 'telefono' => '70686644', 'correo' => 'olivarescorderopao@live.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-25', 'hr' => 9115, 'entidad' => 'ONG BEST BUDDIES BOLIVIA', 'sigla' => 'ONDD', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-115', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-05', 'representante' => 'CARLA AMAYA LORA GONZALES', 'telefono' => '77228109', 'correo' => 'bestbuddiesbolivia@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-26', 'hr' => 9116, 'entidad' => 'FUNDACION ACCION PARA EL DESARROLLO INTEGRAL Y COMUNITARIO BOLIVIA HOY', 'sigla' => 'ADIC BOLIVIA HOY', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-116', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-06', 'representante' => 'MARIA EUFEMIA LOPEZ ARANDA', 'telefono' => '72077207', 'correo' => 'adicboliviahoy@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-27', 'hr' => 9117, 'entidad' => 'ERI', 'sigla' => 'ERI', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-117', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-07', 'representante' => 'LUDWING ERNESTO TORRES CARRASCO', 'telefono' => '72540105', 'correo' => 'fundacion.eri@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-28', 'hr' => 9118, 'entidad' => 'CAMARA BOLIVIANA DE POLIMEROS', 'sigla' => 'CABOPO', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-118', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-08', 'representante' => 'SUSANA MOREIRA MEDRANO', 'telefono' => '69962368', 'correo' => 'decosbolivia@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-29', 'hr' => 9119, 'entidad' => 'FUNDACION BICENTENARIO', 'sigla' => 'FUNCDA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-119', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-09', 'representante' => 'JUAN ANDRES CLAVIJO ROSPIGLIOSI', 'telefono' => '70110070', 'correo' => 'fundacion.bicentenario.bo@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-04-30', 'hr' => 9120, 'entidad' => 'FEDERACION NACIONAL DE TEQBALL', 'sigla' => 'FNTB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-120', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-10', 'representante' => 'MARIO OSMAR MARAÑON SILES', 'telefono' => '70639630', 'correo' => 'osmarms@mspublicity.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-01', 'hr' => 9121, 'entidad' => 'ASOCIACIÓN CIVIL ENERGEA', 'sigla' => 'ASOC', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-121', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-11', 'representante' => 'HERNANN ZABALA NAOUMOV', 'telefono' => '78929988', 'correo' => 'hznaoumov@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-02', 'hr' => 9122, 'entidad' => 'FEDERACIÓN BOLIVIANA DE DEPORTES ELECTRÓNICOS', 'sigla' => 'FBDE', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-122', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-12', 'representante' => 'RICARDO JOSE CAMILO ALIPAZ LOETZ', 'telefono' => '2796061', 'correo' => 'ricardo.alipaz@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-03', 'hr' => 9123, 'entidad' => 'INSTITUTO TIMOTEO PARA CAPACITACION DE LIDERES - BOLIVIA', 'sigla' => 'INTTIMO', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-123', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-13', 'representante' => 'ADALID RAFAEL HINOJOSA LEDEZMA', 'telefono' => '70582226', 'correo' => 'adalid_hinojosa@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-04', 'hr' => 9124, 'entidad' => 'INSTITUTO DE INVESTIGACION DE APOYO AL DESARROLLO Y LA DESCENTRALIZACION', 'sigla' => 'IIDAD', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-124', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-14', 'representante' => 'VICTOR HUGO SILVESTRE SAAVEDRA MOGRO', 'telefono' => '2246731', 'correo' => 'sev_dent20@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-05', 'hr' => 9125, 'entidad' => 'ASOCIACION BOLIVIANA DE COACHING ONTOLOGICO PROFESIONAL', 'sigla' => 'ABCOP', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-125', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-15', 'representante' => 'CLAUDIA ALEJANDRA JIMENEZ ARAUCO', 'telefono' => '72564810', 'correo' => 'claudiajimenezarauco@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-06', 'hr' => 9126, 'entidad' => 'FUNDACION HIJOS DE LA VIUDA', 'sigla' => 'FUNHIVI', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-126', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-16', 'representante' => 'OSVALDO ADRIAN JIMENEZ DE LA TORRE', 'telefono' => '70715430', 'correo' => 'ovis30@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-07', 'hr' => 9127, 'entidad' => 'NO ESTAMOS SOLAS', 'sigla' => 'NES', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-127', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-17', 'representante' => 'YOVANKA ISABEL FRANCO BOTELLO', 'telefono' => '67151670', 'correo' => 'f_yovanka@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-08', 'hr' => 9128, 'entidad' => 'FUNDACION EXPORTAR', 'sigla' => 'FUN', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-128', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-18', 'representante' => 'CARLOS FERNANDO GUILLEN BOLAND', 'telefono' => '3335151', 'correo' => 'f_yovanka@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-09', 'hr' => 9129, 'entidad' => 'FUNDACION OBSERVATORIO DE JURISPRUDENCIA', 'sigla' => 'DFOBS', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-129', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-19', 'representante' => 'GREGORIO MARCELINO CALLISAYA APAZA', 'telefono' => '720090531', 'correo' => 'callisayagreg@yahoo.com ', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-10', 'hr' => 9130, 'entidad' => 'ONG MOVIMIENTO A LA IGUALDAD SOCIAL', 'sigla' => 'MAIS', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-130', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-20', 'representante' => 'SERGIO PABLO SUAREZ ORIHUELA ', 'telefono' => '76204426', 'correo' => 'pablo@sponsor.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-11', 'hr' => 9131, 'entidad' => 'ASOCIACION BOLIVIANA DE COMERCIO ELECTRONICO', 'sigla' => 'ABCE', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-131', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-21', 'representante' => 'CARLOS BUSTAMANTE FERNANDEZ ', 'telefono' => '71929347', 'correo' => 'sobofiaf@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-12', 'hr' => 9132, 'entidad' => 'FUNDACION ETAPP (EDUCACION EN TODAS LAS AREAS PRE GRADO Y POST GRADO)', 'sigla' => 'POST ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-132', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-22', 'representante' => 'JUAN ZEGARRA LOPEZ', 'telefono' => '73256262', 'correo' => 'juancitomarx@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-13', 'hr' => 9133, 'entidad' => 'CAMARA AGROENERGETICA BOLIVIANA', 'sigla' => 'CAB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-133', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-23', 'representante' => 'ALBERTO RUBEN CASTRO ZILVETTY ', 'telefono' => '71578215', 'correo' => 'arczilvetty@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-14', 'hr' => 9134, 'entidad' => 'CASA AMANDITA DEL ADULTO MAYOR', 'sigla' => 'CASA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-134', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-24', 'representante' => 'OSCAR AGUILAR ', 'telefono' => '69962368', 'correo' => 'decosbolivia@gmail.com ', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-15', 'hr' => 9135, 'entidad' => 'COMITE DE MUJERES EMPRENDEDORAS Y EMPRESARIAS DE BOLIVIA', 'sigla' => 'CEEB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-135', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-25', 'representante' => 'DAVID MORALES QUEAPE ', 'telefono' => '72723815', 'correo' => 'devimor22360@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-16', 'hr' => 9136, 'entidad' => 'ONG VIVO MI VEJEZ PLENAMENTE - VIVEZ', 'sigla' => 'ONV', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-136', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-26', 'representante' => 'PERCY LOTHER MEDRANO  SAAVEDRA', 'telefono' => '76181811', 'correo' => 'percymedrano@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-17', 'hr' => 9137, 'entidad' => 'ASOCIACION CULTURAL DE ARTISTAS ALTERNATIVOS "COMUNIDAD METAL BOLIVIA"', 'sigla' => 'CMB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-137', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-27', 'representante' => 'DONATO LOPEZ MAMANI', 'telefono' => '730010101', 'correo' => 'drw_telo@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-18', 'hr' => 9138, 'entidad' => 'FEDERACION NACIONAL DE MECANICOS Y RAMAS ANEXAS DE BOLIVIA', 'sigla' => 'FUND138', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-138', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-28', 'representante' => 'MARIA LUISA CHIPANA PAREDES ', 'telefono' => '70185152', 'correo' => 'arczilvetty@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-19', 'hr' => 9139, 'entidad' => 'ASOCIACION NACIONAL DE AFILIADOS A LA CAJA NACIONAL DE SALUD', 'sigla' => 'ANDA-CNS', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-139', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-29', 'representante' => 'DAVID MIGUEL HINOJOSA PANIAGUA ', 'telefono' => '79700092', 'correo' => 'dhinojosapaniagua@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-20', 'hr' => 9140, 'entidad' => 'MOVIMIENTO DE EMERGENCIA NACIONAL POR LA SEGURIDAD SOCIAL', 'sigla' => 'MEN', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-140', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-30', 'representante' => 'JAIME VELASCO ', 'telefono' => '70185152', 'correo' => 'germanwillyssanchez@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-21', 'hr' => 9141, 'entidad' => 'FUNDACIÓN RED RBC - BOLIVIA', 'sigla' => 'FUNR', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-141', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-05-31', 'representante' => 'OMAR MARTIN SANCHEZ VIRREIRA', 'telefono' => '77981485', 'correo' => 'omar_zono@hotmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-22', 'hr' => 9142, 'entidad' => 'ASOCIACIÓN DE NACIONAL DE CRIADORES DE AVESTRUCES DE BOLIVA', 'sigla' => 'ANCAB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-142', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-01', 'representante' => 'GERMAN WILLYS FLORES SANCHEZ ', 'telefono' => '68646809', 'correo' => 'germanwillyssanchez@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-23', 'hr' => 9143, 'entidad' => 'ONG GREEN ACCIONA', 'sigla' => 'FUND143', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-143', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-02', 'representante' => 'WILMA RIOS RIVERA ', 'telefono' => '72578494', 'correo' => 'programa.hazlotu@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-24', 'hr' => 9144, 'entidad' => 'MUJERES MOVIENDO BOLIVIA ENTIDAD CIVIL SIN FINES DE LUCRO', 'sigla' => 'FUND144', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-144', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-03', 'representante' => 'MONICA FELICIDAD QUISPE LOBO', 'telefono' => '2799781', 'correo' => 'lsalvatierra@farmaciachavez.com.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-25', 'hr' => 9145, 'entidad' => 'ONG AVE DE CRISTAL', 'sigla' => 'FUND145', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-145', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-04', 'representante' => 'FERNANDO VICTOR ZEBALLOS ', 'telefono' => '72511636', 'correo' => 'f.zeballos.gutierrez@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-26', 'hr' => 9146, 'entidad' => 'ONG ILLA', 'sigla' => 'FUND146', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-146', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-05', 'representante' => 'SANDRA LILY CALVET ARANDIA ', 'telefono' => '70108670', 'correo' => 'calvetsandra@hotmail.es', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-27', 'hr' => 9147, 'entidad' => 'FUNDACIÓN BLOOM', 'sigla' => 'FUND147', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-147', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-06', 'representante' => 'EDWIN POOL MARQUEZ PINTO ', 'telefono' => '69962368', 'correo' => 'decosbolivia@gmail.com ', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-28', 'hr' => 9148, 'entidad' => 'GRUPO DE INVESTIGACIÓN Y MONITOREO DE LA TIERRA Y DESARROLLO ECONÓMICO  ENTIDAD CIVIL SIN FINES DE LUCRO', 'sigla' => 'GEOTESA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-148', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-07', 'representante' => 'JOSE FRANCISCO LOVERA TIÑINI ', 'telefono' => '4367047', 'correo' => 'decosbolivia@gmail.com ', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-29', 'hr' => 9149, 'entidad' => 'ONG ACCIÓN VOLUNTARIA LUTERANA EN BOLIVIA – XAKAWI', 'sigla' => 'AVLeB-XAKAWI', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-149', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-08', 'representante' => 'JOSE LUIS CAMACHO MIJERENDINO ', 'telefono' => '70813504', 'correo' => 'vescalante@corporacionjuridica.com.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-30', 'hr' => 9150, 'entidad' => 'FUNDACION DARTE AMOR', 'sigla' => 'FUNDAMOR', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-150', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-09', 'representante' => 'JOSE LUIS CAMACHO MISERENDINO', 'telefono' => '70813504', 'correo' => 'vescalante@corporacionjuridica.com.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-05-31', 'hr' => 9151, 'entidad' => 'FUNDACIÓN AYNIKUNA, COMUNIDAD DE ESTUDIOS Y TRABAJO', 'sigla' => 'FACET', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-151', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-10', 'representante' => 'JOSE LUIS CAMACHO MISERENDINO', 'telefono' => '70813504', 'correo' => 'vescalante@corporacionjuridica.com.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-06-01', 'hr' => 9152, 'entidad' => 'ONG ECOLOGÍA Y NATURALEZA', 'sigla' => 'ECONAT', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-152', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-11', 'representante' => 'RENATA BRAÑEZ VILLEGAS', 'telefono' => '77709492', 'correo' => 'rena.maye@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-06-02', 'hr' => 9153, 'entidad' => 'FEDERACIÓN BOLIVIANA DISCAPACIDAD PSIQUICA, SALUD MENTAL Y FAMILIARES', 'sigla' => 'FEBOLDIPSI ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-153', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-12', 'representante' => 'LUIS FERNANDO MENDIETA ', 'telefono' => '68157274', 'correo' => 'giogismondi@yahoo.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-06-03', 'hr' => 9154, 'entidad' => 'ORGANIZACIÓN NACIONAL DE MEDICOS BOLIVIANOS GRADUADOS EN VENEZUELA', 'sigla' => 'ONAMEBG-VE', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-154', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-13', 'representante' => 'ELIANA BERTON G.', 'telefono' => '78041086', 'correo' => 'vescalante@corporacionjuridica.com.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-06-04', 'hr' => 9155, 'entidad' => 'FEDERACIÓN BOLIVIANA DE WUSHU-KUNG FU', 'sigla' => 'FBWKF', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-155', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-14', 'representante' => 'RAUL FEDERICO SAAVEDRA QUIROGA', 'telefono' => '78041086', 'correo' => 'vescalante@corporacionjuridica.com.bo', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-06-05', 'hr' => 9156, 'entidad' => 'ASOCIACIÓN DE COMERCIANTES DEL CARBON “10 DE NOVIEMBRE”', 'sigla' => 'A.C.C.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-156', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-15', 'representante' => 'CHRISTIAN ANDRES GONZALES CALLA', 'telefono' => '77742722', 'correo' => 'lucianolucchesi@icei.it', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-06-06', 'hr' => 9157, 'entidad' => 'FUNDACIÓN AMAZONICA PARA EL DESARROLLO', 'sigla' => 'FAD', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-157', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-16', 'representante' => 'SHIRLEY FRANCO RODRIGUEZ ', 'telefono' => '70732334', 'correo' => 'espacioeges@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-06-07', 'hr' => 9158, 'entidad' => 'VENEZOLANOS RESIDENTES EN BOLIVIA', 'sigla' => 'VRB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-158', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-17', 'representante' => 'FRANCISCO SAMUEL BARBOSA DA SILVA', 'telefono' => '60522829', 'correo' => 'ordencapellanbolivia@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-06-08', 'hr' => 9159, 'entidad' => 'CÁMARA BINACIONAL DE COMERCIO E INDUSTRIA BOLIVIANO COLOMBIANA', 'sigla' => 'CABOCO', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-159', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-18', 'representante' => 'MARIBEL MARINA HUANCA ', 'telefono' => '60500077', 'correo' => 'espacioeges@gmail.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-06-09', 'hr' => 9160, 'entidad' => 'COLEGIO DE FISIOTERAPIA Y KINESIOLOGIA DE BOLIVIA', 'sigla' => 'COFYKBOL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-160', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-19', 'representante' => 'VICTOR FERNANDO ARMAZA PACHECO', 'telefono' => '77605382', 'correo' => 'salomon.eid@berkeley.edu', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'user_administrativo_id' => 1,]);
        ReservaOtorgacion::create(['fecha_reg' => '2022-06-10', 'hr' => 9161, 'entidad' => 'ASOCIACIÓN NACIONAL DE ENTRENADORES DEL FUTBOL BOLIVIANO', 'sigla' => 'A.N.E.F.B.O.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-161', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-20', 'representante' => 'JOHAN UDALRICO ZAMBRANA OVANDO', 'telefono' => '3350707', 'correo' => 'johan.zambrana@zambranaabogados.com', 'estado' => 2, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'user_administrativo_id' => 1,]);
    
    }
}
