<?php

namespace Database\Seeders;

use App\Models\Registro;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegistroOtorgadosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Registro::create(['fecha_reg' => '2022-06-11', 'hr' => 9162, 'entidad' => 'ORDEN NACIONAL DE CAPELLANES DE BOLIVIA', 'sigla' => 'O.C.B.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-162', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-21', 'representante' => 'MARIA BELEN GUERRA FLORES ', 'telefono' => '76400789', 'correo' => 'belguerra_23hotmail.com ', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 111,]);
        Registro::create(['fecha_reg' => '2022-06-12', 'hr' => 9163, 'entidad' => 'PROGRAMA DEPORTIVO DE BOLIVIA', 'sigla' => 'PRODEBOL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-163', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-22', 'representante' => 'APOLINAR POMA CHURATA', 'telefono' => '65168972', 'correo' => 'electronico:carmenconsultor@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 112,]);
        Registro::create(['fecha_reg' => '2022-06-13', 'hr' => 9164, 'entidad' => 'ASOCIACIÓN NACIONAL DE PADRES DE FAMILIA DE COLEGIOS PRIVADOS DE BOLIVIA - ASOPPFF-BOL', 'sigla' => 'ASOPPFF-BOL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-164', 'naturaleza' => 'ORGANIZACIÓN SOCIAL', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-23', 'representante' => 'GUSTAVO ALBERTO GARCIA UGARTE', 'telefono' => '73277626', 'correo' => 'rbalderrama@bancoecofuturo.com.bo', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 113,]);
        Registro::create(['fecha_reg' => '2022-06-14', 'hr' => 9165, 'entidad' => 'CÁMARA BINACIONAL DE COMERCIO E INDUSTRIA BOLIVIANO PARAGUAYA', 'sigla' => 'CCIBOLPAR ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-165', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-24', 'representante' => 'MARIO ELISEO PAREDES VARGAS ', 'telefono' => '69962368', 'correo' => 'decosbolivia@gmail.com ', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 114,]);
        Registro::create(['fecha_reg' => '2022-06-15', 'hr' => 9166, 'entidad' => 'FUNDACIÓN PROFESIONALES SIN FRONTERAS', 'sigla' => 'FUN-PROSIFRO', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-166', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-25', 'representante' => 'MIGUEL ANGEL MENDOZA AGUILAR', 'telefono' => '73206794', 'correo' => 'mimundozz033@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 115,]);
        Registro::create(['fecha_reg' => '2022-06-16', 'hr' => 9167, 'entidad' => 'FUNDACIÓN “DOMITILA CHUNGARA”', 'sigla' => 'FUNDOCHU', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-167', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-26', 'representante' => 'PATRICIA OREIDA MENDOZA COLQUE', 'telefono' => '77209720', 'correo' => 'patriciaburgoa2019@yahoo.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 116,]);
        Registro::create(['fecha_reg' => '2022-06-17', 'hr' => 9168, 'entidad' => 'ONG ALIANZA ESTRATEGICA PARA EL DESARROLLO SOSTENIBLE', 'sigla' => 'A.E.D.S.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-168', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-27', 'representante' => 'ANA GABRIELA MONTOYA SALINAS', 'telefono' => '75392901', 'correo' => 'camebolorg@gmail.com ', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 117,]);
        Registro::create(['fecha_reg' => '2022-06-18', 'hr' => 9169, 'entidad' => 'ASOCIACIÓN BOLIVIANA DE PADRES DE FAMILIA', 'sigla' => 'FUND169', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-169', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-28', 'representante' => 'ILLA AYMA YURISA DITMEYER-MOREAU', 'telefono' => '67166606', 'correo' => 'illa.ditmeyermoreau@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 118,]);
        Registro::create(['fecha_reg' => '2022-06-19', 'hr' => 9170, 'entidad' => 'ASOCIACIÓN DE TRANSPORTE “AULLAGAS PUENTE DE PLATA”', 'sigla' => 'FUND170', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-170', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-29', 'representante' => 'ELIANA BURGOS CESPEDES', 'telefono' => '78521862', 'correo' => 'noni_impar@hotmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 119,]);
        Registro::create(['fecha_reg' => '2022-06-20', 'hr' => 9171, 'entidad' => 'ONG CENTRO DE PROMOCIÓN PARA EL DESARROLLO SOSTENIBLE', 'sigla' => 'C-PRODES', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-171', 'naturaleza' => 'ONG', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-06-30', 'representante' => 'WILBERTH BARRAL', 'telefono' => '68140068', 'correo' => 'asomedbol@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 120,]);
        Registro::create(['fecha_reg' => '2022-06-21', 'hr' => 9172, 'entidad' => 'CÁMARA NACIONAL INMOBILIARIA', 'sigla' => 'CNI', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-172', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-01', 'representante' => 'CESAR CASTRO CLAURE ', 'telefono' => '73286328', 'correo' => 'sailingbol77@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 121,]);
        Registro::create(['fecha_reg' => '2022-06-22', 'hr' => 9173, 'entidad' => 'FUNDACIÓN TIERRA SIN MAL', 'sigla' => 'F.T.S.M.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-173', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-02', 'representante' => 'FERNANDO DANIEL VILLAFUERTE PHILIPPSBORN', 'telefono' => '72061845', 'correo' => 'feruph@hotmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 122,]);
        Registro::create(['fecha_reg' => '2022-06-23', 'hr' => 9174, 'entidad' => 'CENTRO DEPORTIVO MULTIDISCIPLINARIO QUIRQUINCHO', 'sigla' => 'CDMQ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-174', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-03', 'representante' => 'LUIS FERRUFINO MIRANDA', 'telefono' => '72061845', 'correo' => 'sgantier@emba.com.bo', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 123,]);
        Registro::create(['fecha_reg' => '2022-06-24', 'hr' => 9175, 'entidad' => 'FUNDACION ECO REGION AMAZONICA DE BOLIVIA', 'sigla' => 'FERA-BOLIVIA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-175', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-04', 'representante' => 'ARIEL ZEBALLOS ALABY', 'telefono' => '75031300', 'correo' => 'sgantier@emba.com.bo', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 124,]);
        Registro::create(['fecha_reg' => '2022-06-25', 'hr' => 9176, 'entidad' => 'ASOCIACIÓN BOLIVIANA DE FUTSAL', 'sigla' => 'ABFS', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-176', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-05', 'representante' => 'TED SILVER SARAVIA YUGARANI', 'telefono' => '70679125', 'correo' => 'tedsilver.sy@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 125,]);
        Registro::create(['fecha_reg' => '2022-06-26', 'hr' => 9177, 'entidad' => 'ISTITUTO COOPERAZIONE ECONOMICA INTERNAZIONALE', 'sigla' => 'ICEI', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-177', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-06', 'representante' => 'LUZ MARINA GUTIERREZ REGUERIN ', 'telefono' => '78112784', 'correo' => 'nicolasvalverde@wayarabogados.bo', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 126,]);
        Registro::create(['fecha_reg' => '2022-06-27', 'hr' => 9178, 'entidad' => 'FUNDACIÓN CARLA LUCIA', 'sigla' => 'F.C.L.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-178', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-07', 'representante' => 'MARIO ANGEL DELGADO JIMENEZ', 'telefono' => '79623253', 'correo' => 'mardeljim@hotmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 127,]);
        Registro::create(['fecha_reg' => '2022-06-28', 'hr' => 9179, 'entidad' => 'FUNDACIÓN MADRE TIERRA', 'sigla' => 'FMT', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-179', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-08', 'representante' => 'PEDRO CADENA FLORES', 'telefono' => '73732926', 'correo' => 'colegiogastronomosbolivia@gmail,com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 128,]);
        Registro::create(['fecha_reg' => '2022-06-29', 'hr' => 9180, 'entidad' => 'SOCIEDAD BIBLICA TRINITARIA', 'sigla' => 'FUND180', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-180', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-09', 'representante' => 'ESTEBAN ALFREDO PATI PARI', 'telefono' => '74029917', 'correo' => 'hmenchaca@hotmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 129,]);
        Registro::create(['fecha_reg' => '2022-06-30', 'hr' => 9181, 'entidad' => 'FUNDACIÓN GESTAR', 'sigla' => 'FUND181', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-181', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-10', 'representante' => 'ALEXINA FLORES GALLEGOS', 'telefono' => '69830436', 'correo' => 'aflores@cnda.org.bo', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 130,]);
        Registro::create(['fecha_reg' => '2022-07-01', 'hr' => 9182, 'entidad' => 'FUNDACIÓN ALIANZA PARA LA PAZ Y EL DESARROLLO', 'sigla' => 'APD', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-182', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-11', 'representante' => 'JOSE LUIS QUENALLATA QUENALLATA', 'telefono' => '71577245', 'correo' => '2000afaupea2003@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 131,]);
        Registro::create(['fecha_reg' => '2022-07-02', 'hr' => 9183, 'entidad' => 'CÁMARA BOLIVIANA DE POLÍMEROS', 'sigla' => 'CABOPO', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-183', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-12', 'representante' => 'FOSTER MARAÑON SALINAS ', 'telefono' => '68049394', 'correo' => 'drfostermaranon@gmail.com ', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 132,]);
        Registro::create(['fecha_reg' => '2022-07-03', 'hr' => 9184, 'entidad' => 'FUNDACIÓN NUEVO AMANECER SAN CRISTOBAL TOURS', 'sigla' => 'FUND184', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-184', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-13', 'representante' => 'MARIA DE LA ESPERANZA LANDIVAR POLO', 'telefono' => '77718206', 'correo' => 'cabolotm@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 133,]);
        Registro::create(['fecha_reg' => '2022-07-04', 'hr' => 9185, 'entidad' => 'ASOCIACIÓN NACIONAL DE PROFESIONALES DEL PROCESO DE CAMBIO', 'sigla' => 'A.N.P.P.C.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-185', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-14', 'representante' => 'LUZ MARINA GUTIERREZ REGUERIN', 'telefono' => '78112784', 'correo' => 'nicolasvalverde@wayarabogados.bo', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 134,]);
        Registro::create(['fecha_reg' => '2022-07-05', 'hr' => 9186, 'entidad' => 'ASOCIACIÓN BOLIVIANA DE DESARROLLADORES DE VIDEOJUEGOS', 'sigla' => 'A.B.V.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-186', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-15', 'representante' => 'LUZ MARINA GUTIERREZ REGUERIN', 'telefono' => '78112784', 'correo' => 'luzgutierrez@wayarabogados.bo', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 135,]);
        Registro::create(['fecha_reg' => '2022-07-06', 'hr' => 9187, 'entidad' => 'FUNDACIÓN SEMILLAS CULTURALES', 'sigla' => 'FUND187', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-187', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-16', 'representante' => 'KATHERINE ROSARIO DEL RIO BRAVO', 'telefono' => '70514101', 'correo' => 'cabiebolivia1@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 136,]);
        Registro::create(['fecha_reg' => '2022-07-07', 'hr' => 9188, 'entidad' => 'CONSTRUYENDO CRITICA BOLIVIANA', 'sigla' => 'CCB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-188', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-17', 'representante' => 'FERNANDO ZEBALLOS GUTIERREZ', 'telefono' => '72511636', 'correo' => 'f.zeballos.gutierrez@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 137,]);
        Registro::create(['fecha_reg' => '2022-07-08', 'hr' => 9189, 'entidad' => 'FEDERACION NACIONAL TEQBALL BOLIVIA', 'sigla' => 'FNTB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-189', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-18', 'representante' => 'RICCARDO GIAVARINI', 'telefono' => '71933142', 'correo' => 'ciledezma@hotmail.com ', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 138,]);
        Registro::create(['fecha_reg' => '2022-07-09', 'hr' => 9190, 'entidad' => 'COLECTIVO PLURINACIONAL DE DESARROLLO INTEGRAL INTI', 'sigla' => 'FUND190', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-190', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-19', 'representante' => 'ERICK HUMBERTO PEINADO MENDEZ', 'telefono' => '75008330', 'correo' => 'peinadohumberto@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 139,]);
        Registro::create(['fecha_reg' => '2022-07-10', 'hr' => 9191, 'entidad' => 'ASOCIACIÓN DE FACULTADES Y CARRERAS DE ARQUITECTURA DE BOLIVIA', 'sigla' => 'AFCAB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-191', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'fecha_entrega' => '2022-07-20', 'representante' => 'ALFREDO SALAZAR TARQUINO', 'telefono' => '2906913', 'correo' => 'alfredo.elalto@gmail.com', 'estado' => 6, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 140,]);
    }
}
