<?php

namespace Database\Seeders;

use App\Models\Registro;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RegistroCaducadosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Registro::create(['fecha_reg' => '2022-07-11', 'hr' => 9192, 'entidad' => 'ORGANIZACIÓN DE TRABAJADORAS SEXUALES DE BOLIVIA', 'sigla' => '“ODES-B”', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-192', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'representante' => 'FERNANDO ZEBALLOS GUTIERREZ', 'telefono' => '72511636', 'correo' => 'f.zeballos.gutierrez@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 141,]);
        Registro::create(['fecha_reg' => '2022-07-12', 'hr' => 9193, 'entidad' => 'FUNDACIÓN CIUDADAN@S EN ACCIÓN', 'sigla' => 'FUND193', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-193', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'JARHLIN VARGAS TERRAZAS', 'telefono' => '70009164', 'correo' => 'camaranacionalinmobiliariabolivia@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 142,]);
        Registro::create(['fecha_reg' => '2022-07-13', 'hr' => 9194, 'entidad' => 'ACTIVISTAS, PACIENTES Y EX PACIENTES CONTRA LA TUBERCULOSIS BOLIVIA', 'sigla' => 'ASPACONT-BOLIVIA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-194', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'JUAN STANISLAO VILLEGAS', 'telefono' => '67006883', 'correo' => 'thva_t@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 143,]);
        Registro::create(['fecha_reg' => '2022-07-14', 'hr' => 9195, 'entidad' => 'ASOCIACIÓN DE PRODUCTORES DE HORTALIZAS DE LOS VALLES DEL SUR DE BOLIVIA', 'sigla' => 'APROHOVASUR', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-195', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'TEDDY HENRY VILLCA ALVINO ', 'telefono' => '75276377', 'correo' => 'thva_t@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 144,]);
        Registro::create(['fecha_reg' => '2022-07-15', 'hr' => 9196, 'entidad' => 'ORGANIZACIÓN CORRIENTE 21', 'sigla' => 'OC21', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-196', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'representante' => 'CARLOS MERINO TROCHE', 'telefono' => '69722905', 'correo' => 'carlosmerino40@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 145,]);
        Registro::create(['fecha_reg' => '2022-07-16', 'hr' => 9197, 'entidad' => 'FUNDACIÓN AJAYU CENTRO INTEGRAL', 'sigla' => 'FUND197', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-197', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'representante' => 'OMAR BLACUTT VIVIAN ', 'telefono' => '78004138', 'correo' => 'omarblacutt@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 146,]);
        Registro::create(['fecha_reg' => '2022-07-17', 'hr' => 9198, 'entidad' => 'ASOCIACIÓN BOLIVIANA DE CRIADORES DE SANTA INÉS Y DORPER', 'sigla' => 'ABSID', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-198', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'OMAR BLACUTT VIVIAN ', 'telefono' => '78004138', 'correo' => 'omarblacutt@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 147,]);
        Registro::create(['fecha_reg' => '2022-07-18', 'hr' => 9199, 'entidad' => 'FUNDACIÓN PATRIA GRANDE', 'sigla' => 'FAD', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-199', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'representante' => 'TITO RONALD ARAMAYO CARBALLO', 'telefono' => '76083782', 'correo' => 'ronald_arac@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 148,]);
        Registro::create(['fecha_reg' => '2022-07-19', 'hr' => 9200, 'entidad' => 'CASA AMANDITA DEL ADULTO MAYOR', 'sigla' => 'CASA AMANDITA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-200', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'ANGELICA BLANCA ECHALAR ', 'telefono' => '70781116', 'correo' => 'angelica_echalar@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 149,]);
        Registro::create(['fecha_reg' => '2022-07-20', 'hr' => 9201, 'entidad' => 'GRUPO OPERATIVO DE VOLUNTARIOS', 'sigla' => 'G.O.V.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-201', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'representante' => 'CHRISTIAN MOISES CORTES PEREZ', 'telefono' => '78933653', 'correo' => 'christian_moises1@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 150,]);
        Registro::create(['fecha_reg' => '2022-07-21', 'hr' => 9202, 'entidad' => 'FUNDACIÓN MISION PAIS', 'sigla' => 'MIPAIS', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-202', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'DANIELA ARLETTE MORALES MORENO ', 'telefono' => '73009870', 'correo' => 'venmundo.bolivia@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 151,]);
        Registro::create(['fecha_reg' => '2022-07-22', 'hr' => 9203, 'entidad' => 'ASOCIACIÓN DE INTEGRACIÓN DIPLOMÁTICA EN BOLIVIA', 'sigla' => 'AIDB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-203', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'representante' => 'CINTIA MONICA PEÑALOZA SUAREZ', 'telefono' => '730045554', 'correo' => 'venmundo.bolivia@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 152,]);
        Registro::create(['fecha_reg' => '2022-07-23', 'hr' => 9204, 'entidad' => 'FUNDACIÓN UNIDOS POR LA SOLIDARIDAD', 'sigla' => 'UN-SOL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-204', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'DUBERTY FLORES MAMANI ', 'telefono' => '73009870', 'correo' => 'deportistas.asociacion@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 153,]);
        Registro::create(['fecha_reg' => '2022-07-24', 'hr' => 9205, 'entidad' => 'ONG VIVO MI VEJEZ PLENAMENTE', 'sigla' => 'VIVEZ', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-205', 'naturaleza' => 'ENTIDAD SIN FINES DE LUCRO', 'obs' => 'sin observacion', 'representante' => 'SUSANA MOREIRA ', 'telefono' => '69962368', 'correo' => 'deportistas.asociacion@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 154,]);
        Registro::create(['fecha_reg' => '2022-07-25', 'hr' => 9206, 'entidad' => 'CÁMARA NACIONAL DE EVENTOS Y SERVICIOS NOCTURNOS BOLIVIA', 'sigla' => 'C.A.N.E.S.B.O.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-206', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'JUAN JOSE YAÑEZ TORREZ', 'telefono' => '69962368', 'correo' => 'camaranacionalinmobiliariabolivia@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 155,]);
        Registro::create(['fecha_reg' => '2022-07-26', 'hr' => 9207, 'entidad' => 'PROMOTORES MUSICALES BOLIVIA SANTA CECILIA - PROBOLSC', 'sigla' => 'PROBOLSC', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-207', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'LUIS ENRIQUE GONZALO ITURRALDE MORENO', 'telefono' => '69720300', 'correo' => 'liturralde@kantutani.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 156,]);
        Registro::create(['fecha_reg' => '2022-07-27', 'hr' => 9208, 'entidad' => 'ORGANIZACIÓN DEL ALBA BOLIVIA DE ORIENTE A OCCIDENTE “QHANA AMUYUMPI”', 'sigla' => 'ODABOL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-208', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'JUAN CARLOS MEDRANO GONZALES ', 'telefono' => '69213344', 'correo' => 'camaranacionalinmobiliariabolivia@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 157,]);
        Registro::create(['fecha_reg' => '2022-07-28', 'hr' => 9209, 'entidad' => 'FEDERACIÓN NACIONAL DE HIPOACÚSICOS BOLIVIA', 'sigla' => 'FENAHIBO', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-209', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'FRANKLIN REYNALDO RODRIGUEZ COARITE', 'telefono' => '77284724', 'correo' => 'info@vivaboliviaps.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 158,]);
        Registro::create(['fecha_reg' => '2022-07-29', 'hr' => 9210, 'entidad' => 'FUNDACIÓN ENERGIA Y DESARROLLO', 'sigla' => 'E&D', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-210', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'GRISEL VICTORIA CARVAJAL ROJAS', 'telefono' => '76003577', 'correo' => 'wjmendez@emprendedores.bo', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 159,]);
        Registro::create(['fecha_reg' => '2022-07-30', 'hr' => 9211, 'entidad' => 'ONG PRO DERECHOS HUMANOS-BOLIVIA', 'sigla' => 'ORPDEHBOL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-211', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'JAMIL MIRKO PARDO CHAVEZ', 'telefono' => '70009164', 'correo' => 'camaranacionalinmobiliariabolivia@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 160,]);
        Registro::create(['fecha_reg' => '2022-07-31', 'hr' => 9212, 'entidad' => 'COLEGIO DE PROFESIONALES GASTRÓNOMICOS DE BOLIVIA', 'sigla' => 'CPGB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-212', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'CLAUDIA ANDREA GARCIA GARCIA PAZ ', 'telefono' => '70721897', 'correo' => 'claudiagarciapaz@gmail.com ', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 161,]);
        Registro::create(['fecha_reg' => '2022-08-01', 'hr' => 9213, 'entidad' => 'FUNDACIÓN BOLIVIA PARA EL MUNDO', 'sigla' => 'FUNBOLPAMU', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-213', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'HELEN AMGELICA RODRIGUEZ CORNEJO ', 'telefono' => '65429766', 'correo' => 'jannethdylan@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 162,]);
        Registro::create(['fecha_reg' => '2022-08-02', 'hr' => 9214, 'entidad' => 'ONG ASOCIACIÓN NACIONAL DE ADULTOS MAYORES LGBTI - BOLIVIA', 'sigla' => 'FUND214', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-214', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'JAVIER CARLOS DURAN PEREZ', 'telefono' => '72534342', 'correo' => 'jdrecursoshumanos@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 163,]);
        Registro::create(['fecha_reg' => '2022-08-03', 'hr' => 9215, 'entidad' => 'WOMEN IN MINING BOLIVIA', 'sigla' => 'WIM', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-215', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'INGRID ALEJANDRA SANCHEZ CARDOZO', 'telefono' => '79821225', 'correo' => 'ingrid@herrerabogados.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 164,]);
        Registro::create(['fecha_reg' => '2022-08-04', 'hr' => 9216, 'entidad' => 'ONG CENTRO INTERDISCIPLINARIO PARA EMPRENDIMIENTOS EN LA REVALORIZACIÓN DE LA GESTIÓN INTEGRAL DEL AGUA ', 'sigla' => 'CINERGIA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-216', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'RICARDO DENIS VELASCO PAREJAS', 'telefono' => '77311722', 'correo' => 'presidencia@abce.org.bo', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 165,]);
        Registro::create(['fecha_reg' => '2022-08-05', 'hr' => 9217, 'entidad' => 'ASOCIACIÓN DE DIPLOMÁTICOS DEL ESTADO PLURINACIONAL DE BOLIVIA', 'sigla' => 'ADEPB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-217', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'LASTENIA ELIS AYAVIRI ALVAREZ', 'telefono' => '69911995', 'correo' => 'espacioeges@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 166,]);
        Registro::create(['fecha_reg' => '2022-08-06', 'hr' => 9218, 'entidad' => 'CÁMARA EMPRESARIAL BOLIVIANA DE BIENES RAICES', 'sigla' => 'CEBIR', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-218', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'ANA MARIA SANCHEZ MOLINA', 'telefono' => '73646561', 'correo' => 'ana_msm@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 167,]);
        Registro::create(['fecha_reg' => '2022-08-07', 'hr' => 9219, 'entidad' => 'ASOCIACIÓN BOLIVIANA DE CRIPTOTECNOLOGIAS Y BLOCKCHAIN', 'sigla' => 'ABCYB', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-219', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'ANTONIO ALBERTO CASSAP URZAGASTE', 'telefono' => '76181811', 'correo' => 'beto_cassap@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 168,]);
        Registro::create(['fecha_reg' => '2022-08-08', 'hr' => 9220, 'entidad' => 'TRANSPARENCIA BOLIVIA', 'sigla' => 'TRANSP-BOL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-220', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'LOURDES ANDREA FERNANDEZ BLACUTT', 'telefono' => '74729959', 'correo' => 'andreafernandezblacutt@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 169,]);
        Registro::create(['fecha_reg' => '2022-08-09', 'hr' => 9221, 'entidad' => 'FUNDACIÓN AYNIKUNA, COMUNIDAD DE ESTUDIOS Y TRABAJO', 'sigla' => 'FACET', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-221', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'EDWIN POOL MARQUEZ PINTO', 'telefono' => '69962368', 'correo' => 'decosbolivia@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 170,]);
        Registro::create(['fecha_reg' => '2022-08-10', 'hr' => 9222, 'entidad' => 'ASOCIACIÓN DE COMERCIANTES DEL CARBON “10 DE NOVIEMBRE”', 'sigla' => 'A.C.C.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-222', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'CARMEN ISABEL HURTADO AZURDUY', 'telefono' => '8001007707', 'correo' => 'ihurtado@trebol.com.bo', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 171,]);
        Registro::create(['fecha_reg' => '2022-08-11', 'hr' => 9223, 'entidad' => 'ONG PODER FEMENINO Y DEPORTE', 'sigla' => 'FEMPODERA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-223', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'JIMMY R. HILARI MAMANI', 'telefono' => '72985108', 'correo' => 'camaracbch@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PA', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 172,]);
        Registro::create(['fecha_reg' => '2022-08-12', 'hr' => 9224, 'entidad' => 'SAN VICENTE DE PAUL', 'sigla' => 'S.V.P.', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-224', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'CHRISTIAN EDUARDO MONJE', 'telefono' => '74057667', 'correo' => 'nandeboliviaddhh@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'TJ', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 173,]);
        Registro::create(['fecha_reg' => '2022-08-13', 'hr' => 9225, 'entidad' => 'ONG VENEBOL', 'sigla' => 'FUND225', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-225', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'JAVIER SOCRATES VALDA MIRANDA', 'telefono' => '79551847', 'correo' => 'alinepat@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CH', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 174,]);
        Registro::create(['fecha_reg' => '2022-08-14', 'hr' => 9226, 'entidad' => 'FUNDACIÓN EMPODERA', 'sigla' => 'FEMPODERA', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-226', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'JOSE RUDY GALIER MACHACA', 'telefono' => '76203794', 'correo' => 'jose_rgalier@hotmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'LP', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 175,]);
        Registro::create(['fecha_reg' => '2022-08-15', 'hr' => 9227, 'entidad' => 'CENTRAL UNICA DE TRABAJADORES POR CUENTA PROPIA DE BOLIVIA - CETRABOL', 'sigla' => 'FUND227', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-227', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'ANA MARIA ARANIBAR', 'telefono' => '70684024', 'correo' => 'winbolivia2019@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'OR', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 176,]);
        Registro::create(['fecha_reg' => '2022-08-16', 'hr' => 9228, 'entidad' => 'VIRTUAL EDUCA BOLIVIA ', 'sigla' => 'FUND228', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-228', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'SEBASTIAN ANDRES ARZE PANDO', 'telefono' => '76400789', 'correo' => 'mariabelenguerraflores@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'PT', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 177,]);
        Registro::create(['fecha_reg' => '2022-08-17', 'hr' => 9229, 'entidad' => 'FUNDACION ETAPP (EDUCACION EN TODAS LAS AREAS PRE GRADO Y POST GRADO)', 'sigla' => 'ETAPP', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-229', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'RUBEN FELIPE PINTO VARGAS', 'telefono' => '79153605', 'correo' => 'rubenpintovargas@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'CB', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 178,]);
        Registro::create(['fecha_reg' => '2022-08-18', 'hr' => 9230, 'entidad' => 'FUNDACION CIUDAD HUMANA', 'sigla' => 'FUND230', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-230', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'MIGUEL ANGEL GUMICIO NOGUEDA', 'telefono' => '69009374', 'correo' => 'mgumucio@ppolegal.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'SC', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 179,]);
        Registro::create(['fecha_reg' => '2022-08-19', 'hr' => 9231, 'entidad' => 'FUNDACIÓN POR LA LIBERTAD', 'sigla' => 'FPL', 'persona_colectiva' => 'PERSONA NATURAL', 'nro_certificado' => '00-231', 'naturaleza' => 'FUNDACION', 'obs' => 'sin observacion', 'representante' => 'RONALD CHAVARRIA ZABALA', 'telefono' => '71626966', 'correo' => 'ronaldchavarriazabala@gmail.com', 'estado' => 5, 'ci_rep' => '1239926', 'ext_ci_rep' => 'BN', 'create_admin' => 1, 'update_admin' => 1, 'administrativo_id' => 1, 'reserva_nombre_id' => 180,]);
    }
}
